import type { NextPage } from "next";
import Head from "next/head";
import { AppShell, Navbar, Progress, Header, Text, Title, Paper } from "@mantine/core";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding="md"
        navbar={
          <Navbar width={{ base: 300 }} height={500} p="xs">
            {/* Navbar content */}
          </Navbar>
        }
        header={
          <Header height={60} p="xs">
            {/* Header content */}
          </Header>
        }
        styles={(theme) => ({
          main: {
            backgroundColor:
              theme.colorScheme === "dark"
                ? theme.colors.dark[8]
                : theme.colors.gray[0],
          },
        })}
      >
        <Title order={1}>Computer Science (MS)</Title>
        <Paper shadow="xs" p="md">
          <Title order={2}>Progress at a Glance</Title>
          <>
            <>
              <Text>45 required, 22 completed, 23 remaining</Text>
              <Progress size="xl" value={50} />
            </>
            <>
              <Text>36 required, 22 completed, 14 remaining</Text>
              <Progress size="xl" value={60} />
            </>
          </>
        </Paper>
      </AppShell>
    </>
  );
};

export default Home;
